###

POST http://localhost:3002/users/signUp
Content-Type: application/json

{
    "name": "Rogelio",
    "email": "emai@ail.com",
    "password": "1234"
}

###

GET http://localhost:3002/users/

###
POST http://localhost:3002/users/logIn
Content-Type: application/json

{
    "email": "emai@ail.com",
    "password": "1234"
}

###
GET http://localhost:3002/v
Authorization: Bearer 

###
POST http://localhost:3002/activity/newActivity/648be7b7fec9178f4c9c0352
Content-Type: application/json

{
    "name": "Actividad 1",
    "status": "Doing"
}

###
GET http://localhost:3002/activity/648be7b7fec9178f4c9c0352

###
PATCH http://localhost:3002/activity/editActivity
Content-Type: application/json

{
    "idUser": "648be7b7fec9178f4c9c0352",
    "idActivity": "2987db28-583a-4748-8a58-52e5d04f90f8",
    "status": "done",
    "name": null
}